notify: Use sane DISPLAY when defined as e. g.,  :0.

diff --git a/scripts/lpf-notify b/scripts/lpf-notify
--- a/scripts/lpf-notify
+++ b/scripts/lpf-notify
@@ -17,7 +17,9 @@ function get_lockdir()
 # Return lock directory for current user and DISPLAY. Requires $DISPLAY.
 {
     [ "$DISPLAY" ] || { echo; return 1; }
-    local lockdir="/var/run/user/$( get_uid )/lpf/$DISPLAY"
+    display="$DISPLAY"
+    [[ "$display" == :* ]] && display="0${display}"
+    local lockdir="/var/run/user/$( get_uid )/lpf/$display"
     [ -d $lockdir ]  || mkdir -p $lockdir
     echo "$lockdir"
 }
@@ -65,7 +67,7 @@ function is_locked()
 function check_pkgbuild_user()
 {
     [ "$USER" != 'pkg-build' ] && {
-        echo >&2 "Error: must be run as pkk-build user."
+        echo >&2 "Error: must be run as pkg-build user."
         exit 1
     }
 }
